#!/bin/sh
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devpts none /dev/pts
# To do NFS-mount of a development host directory for your project,
# replace the IP and host directory in the line below with your
# values matching your local settings
# sleep 3 && mount -o nolock,rsize=1024 172.17.0.1:/home/vlad/test/HEAD/projects /mnt
export PS1="[\u@\h \W]\$ "
ifconfig lo 127.0.0.1
# ifconfig eth0 172.17.0.199


